---

jobs:
  include:
    - stage: Build

      sudo: required
      language: minimal
      services:
        - docker
      script: docker build --build-arg CODECOV_TOKEN .
      after_success:
        - curl -q -sSL --max-time 10 -X POST https://goreportcard.com/checks?repo=github.com/${TRAVIS_REPO_SLUG}

stages:
  - Build

notifications:
  email: false
