jobs:
  include:
  - stage: Build

    sudo: required
    language: minimal
    services:
    - docker
    script: docker build --build-arg CODECOV_TOKEN -t "${DOCKER_USER}/$(make name):$(make version)" .
    after_success:
    - curl -q -sSL --max-time 10 -X POST https://goreportcard.com/checks?repo=github.com/ViBiOh/httputils

stages:
- Build

notifications:
  email: false
