jobs:
  include:
  - stage: Build

    sudo: required
    services:
    - docker
    script: docker build -t vibioh/`make name`:`make version` .
    after_success: |
      curl -s -X POST https://goreportcard.com/checks?repo=github.com/ViBiOh/httputils

stages:
  - Build

notifications:
  email: false
