language: go
go : '1.10'
after_success: |
  bash <(curl -s https://codecov.io/bash)

  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    curl -s -X POST https://goreportcard.com/checks?repo=github.com/ViBiOh/httputils
  fi
notifications:
  email: false
