jobs:
  include:
  - stage: Build

    sudo: required
    services:
    - docker
    script: docker build --build-arg CODECOV_TOKEN -t "vibioh/$(make name):$(make version)" .
    after_success:
    - curl -s -X POST https://goreportcard.com/checks?repo=github.com/ViBiOh/httputils

  - stage: Release

    language: go
    go: 1.12
    env:
      - GO111MODULE=on
      - GITHUB_REPOSITORY=ViBiOh/httputils
      - GIT_TAG=${TRAVIS_TAG}
      - RELEASE_NAME=${TRAVIS_TAG}
    script: ./script/release

stages:
  - Build
  - name: Release
    if: tag =~ /^v\d+\.\d+\.\d+$/

notifications:
  email: false
