[[constraint]]
  branch = "master"
  name = "github.com/opentracing/opentracing-go"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/tdewolff/minify"
  version = "2.3.4"

[prune]
  go-tests = true
  unused-packages = true
