[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/opentracing-contrib/go-stdlib"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.16.0"

[[constraint]]
  name = "github.com/NYTimes/gziphandler"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/tdewolff/minify"
  version = "2.3.6"

[prune]
  go-tests = true
  unused-packages = true
