#!/usr/bin/env sh

set -e

MODE="mode: atomic"

echo "${MODE}" > coverage.out

for pkg in $(go list ./... | grep -v vendor); do
    go test -covermode=atomic -coverprofile=profile.out $pkg

    if [ -f profile.out ]; then
        cat profile.out | grep -v "${MODE}" >> coverage.out || true
        rm profile.out
    fi
done

go tool cover -func=coverage.out
